import { z } from 'zod'
export const segments = {
  dentist: {
    label: 'Dentistas',
    terms: ['dentistas', 'clínica odontológica', 'ortodontista'],
    priority: 8,
    booking: true,
    clientArea: false,
    highTicket: true,
  },
  clinic: {
    label: 'Clínicas',
    terms: ['clínica médica', 'clínica de especialidades', 'centro médico'],
    priority: 8,
    booking: true,
    clientArea: true,
    highTicket: true,
  },
  beauty: {
    label: 'Estética',
    terms: ['clínica de estética', 'estética facial', 'estética corporal'],
    priority: 8,
    booking: true,
    clientArea: false,
    highTicket: true,
  },
  lawyer: {
    label: 'Advogados',
    terms: ['advogados', 'escritório de advocacia'],
    priority: 8,
    booking: true,
    clientArea: true,
    highTicket: true,
  },
  accounting: {
    label: 'Contabilidade',
    terms: ['contabilidade', 'escritório contábil'],
    priority: 8,
    booking: false,
    clientArea: true,
    highTicket: true,
  },
  real_estate: {
    label: 'Imobiliárias',
    terms: ['imobiliária', 'corretora de imóveis'],
    priority: 8,
    booking: false,
    clientArea: true,
    highTicket: true,
  },
  construction: {
    label: 'Construtoras',
    terms: ['construtora', 'construção civil'],
    priority: 8,
    booking: false,
    clientArea: true,
    highTicket: true,
  },
  solar: {
    label: 'Energia Solar',
    terms: ['energia solar', 'instalação de painéis solares'],
    priority: 8,
    booking: false,
    clientArea: false,
    highTicket: true,
  },
  gym: {
    label: 'Academias',
    terms: ['academia', 'centro de treinamento'],
    priority: 5,
    booking: true,
    clientArea: true,
    highTicket: false,
  },
  school: {
    label: 'Escolas',
    terms: ['escola particular', 'escola de idiomas', 'escola de cursos'],
    priority: 5,
    booking: false,
    clientArea: true,
    highTicket: false,
  },
  other: {
    label: 'Outros',
    terms: [],
    priority: 2,
    booking: false,
    clientArea: false,
    highTicket: false,
  },
} as const
export type Segment = keyof typeof segments
export const states = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO',
] as const
export const campaignSchema = z
  .object({
    segment: z.enum(Object.keys(segments) as [Segment, ...Segment[]]),
    customSegment: z.string().trim().max(80).optional(),
    city: z.string().trim().min(2).max(100),
    state: z.enum(states),
    volume: z.union([z.literal(100), z.literal(250), z.literal(500), z.literal(1000)]),
    min_score: z.number().int().min(0).max(100).default(55),
    ai_score_threshold: z.number().int().min(0).max(100).default(85),
  })
  .refine((v) => v.segment !== 'other' || (v.customSegment?.length ?? 0) >= 2, {
    message: 'Informe o segmento personalizado.',
    path: ['customSegment'],
  })
