import {
  Add01Icon,
  PencilEdit01Icon,
  Delete02Icon,
  EyeIcon,
  ViewOffIcon,
  FloppyDiskIcon,
  Cancel01Icon,
  Copy01Icon,
  Download01Icon,
  Upload01Icon,
  Link01Icon,
  ExternalLinkIcon,
  FilterIcon,
  Search01Icon,
  Refresh01Icon,
  More01Icon,
  StarIcon,
  SparklesIcon,
  LockIcon,
  Mail01Icon,
  SlidersHorizontalIcon,
  Exchange01Icon,
  ArrangeIcon,
  File01Icon,
} from '@hugeicons/core-free-icons'

export {
  Add01Icon as AddActionIcon,
  PencilEdit01Icon as EditActionIcon,
  Delete02Icon as DeleteActionIcon,
  EyeIcon as ViewActionIcon,
  ViewOffIcon as HideActionIcon,
  FloppyDiskIcon as SaveActionIcon,
  Cancel01Icon as CancelActionIcon,
  Copy01Icon as DuplicateActionIcon,
  Download01Icon as DownloadActionIcon,
  Upload01Icon as UploadActionIcon,
  Link01Icon as LinkActionIcon,
  ExternalLinkIcon as ExternalLinkActionIcon,
  FilterIcon as FilterActionIcon,
  Search01Icon as SearchActionIcon,
  Refresh01Icon as RefreshActionIcon,
  More01Icon as MoreActionIcon,
  StarIcon as StarActionIcon,
  SparklesIcon as SparklesActionIcon,
  LockIcon as LockActionIcon,
  Mail01Icon as MailActionIcon,
  SlidersHorizontalIcon as ConfigActionIcon,
  Exchange01Icon as SwapActionIcon,
  ArrangeIcon as ReorderActionIcon,
  File01Icon as PdfActionIcon,
}
