import {
  DashboardSquare01Icon,
  Folder01Icon,
  KanbanIcon,
  CalculatorIcon,
  Invoice01Icon,
  Globe02Icon,
  Shield01Icon,
  Settings01Icon,
  Logout01Icon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  Menu01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Home01Icon,
} from '@hugeicons/core-free-icons'

export {
  DashboardSquare01Icon as DashboardNavIcon,
  Folder01Icon as ProjectsNavIcon,
  KanbanIcon as KanbanNavIcon,
  CalculatorIcon as PricingNavIcon,
  Invoice01Icon as QuotesNavIcon,
  Globe02Icon as PortfolioNavIcon,
  Shield01Icon as PermissionsNavIcon,
  Settings01Icon as SettingsNavIcon,
  Logout01Icon as LogoutNavIcon,
  PanelLeftCloseIcon as CollapseSidebarIcon,
  PanelLeftOpenIcon as ExpandSidebarIcon,
  Menu01Icon as MobileMenuIcon,
  ArrowLeft01Icon as BackNavIcon,
  ArrowRight01Icon as ForwardNavIcon,
  ArrowUp01Icon as UpNavIcon,
  ArrowDown01Icon as DownNavIcon,
  Home01Icon as HomeNavIcon,
}
