import {
  CheckmarkCircle01Icon,
  CancelCircleIcon,
  AlertCircleIcon,
  InformationCircleIcon,
  Clock01Icon,
  Shield01Icon,
  CrownIcon,
  UserCheck01Icon,
  UserBlock01Icon,
  Attachment01Icon,
  Calendar01Icon,
  Loading01Icon,
  CheckmarkSquare01Icon,
  LockIcon,
  HelpCircleIcon,
} from '@hugeicons/core-free-icons'

export {
  CheckmarkCircle01Icon as SuccessStatusIcon,
  CancelCircleIcon as ErrorStatusIcon,
  AlertCircleIcon as WarningStatusIcon,
  InformationCircleIcon as InfoStatusIcon,
  Clock01Icon as PendingStatusIcon,
  Shield01Icon as ShieldStatusIcon,
  CrownIcon as AdminStatusIcon,
  UserCheck01Icon as ActiveUserStatusIcon,
  UserBlock01Icon as SuspendedUserStatusIcon,
  Attachment01Icon as FileAttachmentStatusIcon,
  Calendar01Icon as DateStatusIcon,
  Loading01Icon as SpinnerStatusIcon,
  CheckmarkSquare01Icon as CheckedSquareStatusIcon,
  LockIcon as RestrictedStatusIcon,
  HelpCircleIcon as HelpStatusIcon,
}
