import { Project, Technology, ServiceItem, FAQItem, Testimonial, SiteSettings } from '@/types/database.types'

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  id: 'default-settings',
  company_name: 'ANXIS',
  logo_light_url: '/images/logo-transparente.png',
  logo_dark_url: '/images/logo-transparente.png',
  email: 'contato@anxis.com.br',
  phone: '(11) 99999-9999',
  whatsapp: '5511999999999',
  address: 'São Paulo, SP - Brasil',
  social_links: {
    instagram: 'https://instagram.com/anxis.digital',
    linkedin: 'https://linkedin.com/company/anxis-digital',
  },
  primary_cta_label: 'Quero criar meu site',
  primary_cta_url: '#contato',
}

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 's1',
    title: 'Sites Institucionais',
    description: 'Apresente sua empresa com clareza, credibilidade e uma estrutura moderna preparada para gerar novas oportunidades.',
    icon: 'Globe',
    benefits: [
      'Design responsivo sob medida',
      'Otimização de velocidade & SEO',
      'Gestão simples de conteúdos'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 1,
  },
  {
    id: 's2',
    title: 'Landing Pages',
    description: 'Páginas focadas em campanhas de tráfego pago, lançamentos e geração contínua de oportunidades qualificadas.',
    icon: 'Zap',
    benefits: [
      'Estrutura focada em conversão',
      'Rastreamento nativo de UTMs & Meta Pixel',
      'Integração direta com seu CRM'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 2,
  },
  {
    id: 's3',
    title: 'Lojas Virtuais',
    description: 'Projetos de e-commerce voltados para a melhor experiência de compra do cliente e gestão ágil do catálogo.',
    icon: 'ShoppingBag',
    benefits: [
      'Nuvemshop, Tray ou WooCommerce',
      'Checkout otimizado e seguro',
      'Integração com ERPs e fretes'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 3,
  },
  {
    id: 's4',
    title: 'Reformulação de Sites',
    description: 'Modernização de sites legados com melhorias de interface, arquitetura da informação e performance.',
    icon: 'RefreshCw',
    benefits: [
      'Migração segura de SEO',
      'Nova identidade tecnológica',
      'Carregamento instantâneo'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 4,
  },
  {
    id: 's5',
    title: 'Projetos Personalizados',
    description: 'Desenvolvimento em código para demandas complexas e regras de negócio que não cabem em plataformas prontas.',
    icon: 'Code2',
    benefits: [
      'Next.js, React e TypeScript',
      'Arquitetura escalável',
      'APIs e microsserviços sob medida'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 5,
  },
  {
    id: 's6',
    title: 'Integrações e Melhorias',
    description: 'Conexão com ferramentas externas, meios de pagamento, automações de e-mail e melhorias de funcionalidades.',
    icon: 'Cpu',
    benefits: [
      'Automação de processos',
      'Webhooks e APIs RESTful',
      'Suporte técnico contínuo'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 6,
  },
]

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'Dra. Erika Vieira - Dermatologia & Estética Avançada',
    client: 'Dra. Erika Vieira',
    category: 'landing-page',
    short_description: 'Posicionamento médico de alto padrão com design sofisticado, agendamento de consultas facilitado e experiência premium.',
    desktop_image_url: '/images/projects/erika-vieira-dermatologia.webp',
    mobile_image_url: '/images/projects/erika-vieira-dermatologia.webp',
    project_url: 'https://paleturquoise-anteater-706869.hostingersite.com/',
    button_label: 'Ver Projeto Online',
    open_new_tab: true,
    technologies: ['Landing Page', 'Design UI/UX', 'Alta Conversão', 'Mobile First'],
    year: '2026',
    accent_color: '#2D4F48',
    image_alt: 'Preview do projeto Dra. Erika Vieira Dermatologia',
    is_featured: true,
    is_visible: true,
    display_order: 1,
  },
  {
    id: 'p2',
    title: 'Felipe Bezerril - Advocacia & Consultoria Jurídica',
    client: 'Dr. Felipe Bezerril',
    category: 'landing-page',
    short_description: 'Landing page institucional para advocacia com design moderno e sóbrio, autoridade jurídica e direcionamento estratégico para o WhatsApp.',
    desktop_image_url: '/images/projects/felipe-bezerril-advocacia.webp',
    mobile_image_url: '/images/projects/felipe-bezerril-advocacia.webp',
    project_url: 'https://felipebezerril.adv.br/',
    button_label: 'Ver Projeto Online',
    open_new_tab: true,
    technologies: ['Landing Page', 'Alta Conversão', 'Design UI/UX', 'WhatsApp'],
    year: '2026',
    accent_color: '#E6732B',
    image_alt: 'Preview da landing page Felipe Bezerril Advocacia',
    is_featured: true,
    is_visible: true,
    display_order: 2,
  },
  {
    id: 'p3',
    title: 'Slouver Games - E-commerce Gamer & Gift Cards',
    client: 'Slouver Games',
    category: 'e-commerce',
    short_description: 'Loja virtual de alta performance para produtos digitais, Game Pass e Gift Cards com entrega rápida, design dark imersivo e checkout seguro.',
    desktop_image_url: '/images/projects/slouver-games.webp',
    mobile_image_url: '/images/projects/slouver-games.webp',
    project_url: 'https://slouvergames.com.br/',
    button_label: 'Ver Loja Online',
    open_new_tab: true,
    technologies: ['E-commerce', 'Produtos Digitais', 'Checkout Rápido', 'Design Dark'],
    year: '2026',
    accent_color: '#00C968',
    image_alt: 'Preview da loja virtual Slouver Games',
    is_featured: true,
    is_visible: true,
    display_order: 3,
  },
  {
    id: 'p4',
    title: 'RiosMed - Centro Médico & Especialidades Integradas',
    client: 'RiosMed Saúde',
    category: 'landing-page',
    short_description: 'Landing page completa para centro médico e diagnósticos com apresentação clara de especialidades, exames e agendamento.',
    desktop_image_url: '/images/projects/riosmed-saude.webp',
    mobile_image_url: '/images/projects/riosmed-saude.webp',
    project_url: 'https://riosmed.com.br/',
    button_label: 'Ver Projeto Online',
    open_new_tab: true,
    technologies: ['Landing Page', 'SEO Local', 'Agendamento Online', 'Alta Conversão'],
    year: '2026',
    accent_color: '#0099FF',
    image_alt: 'Preview da landing page RiosMed Saúde',
    is_featured: true,
    is_visible: true,
    display_order: 4,
  },
  {
    id: 'p5',
    title: 'Mirele Fabro - Psicologia Materno-Infantil',
    client: 'Mirele Fabro Psicologia',
    category: 'landing-page',
    short_description: 'Landing page acolhedora e persuasiva para psicologia e parentalidade positiva, construída para gerar conexão imediata e captar pacientes.',
    desktop_image_url: '/images/projects/mirele-fabro-psicologia.webp',
    mobile_image_url: '/images/projects/mirele-fabro-psicologia.webp',
    project_url: 'https://mirelefabro.com.br/',
    button_label: 'Ver Projeto Online',
    open_new_tab: true,
    technologies: ['Landing Page', 'Copywriting', 'Design UI/UX', 'Conversão'],
    year: '2026',
    accent_color: '#FF4B72',
    image_alt: 'Preview da Landing Page Mirele Fabro Psicologia',
    is_featured: true,
    is_visible: true,
    display_order: 5,
  },
]

export const INITIAL_TECHNOLOGIES: Technology[] = [
  { id: 't1', name: 'Tray', logo_url: '/logos/tray.svg', category: 'E-commerce', is_visible: true, display_order: 1 },
  { id: 't2', name: 'Nuvemshop', logo_url: '/logos/nuvemshop.svg', category: 'E-commerce', is_visible: true, display_order: 2 },
  { id: 't3', name: 'WordPress', logo_url: '/logos/wordpress.svg', category: 'CMS', is_visible: true, display_order: 3 },
  { id: 't4', name: 'WooCommerce', logo_url: '/logos/woocommerce.svg', category: 'E-commerce', is_visible: true, display_order: 4 },
  { id: 't5', name: 'Next.js', logo_url: '/logos/nextjs.svg', category: 'Framework', is_visible: true, display_order: 5 },
  { id: 't6', name: 'React', logo_url: '/logos/react.svg', category: 'Frontend', is_visible: true, display_order: 6 },
  { id: 't7', name: 'TypeScript', logo_url: '/logos/typescript.svg', category: 'Linguagem', is_visible: true, display_order: 7 },
  { id: 't8', name: 'Tailwind CSS', logo_url: '/logos/tailwindcss.svg', category: 'Styling', is_visible: true, display_order: 8 },
  { id: 't9', name: 'Supabase', logo_url: '/logos/supabase.svg', category: 'Backend', is_visible: true, display_order: 9 },
  { id: 't10', name: 'Node.js', logo_url: '/logos/nodejs.svg', category: 'Backend', is_visible: true, display_order: 10 },
]

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'f1',
    question: 'Quanto custa desenvolver um site ou loja virtual?',
    answer: 'O investimento varia conforme a complexidade, número de páginas, integrações necessárias e se o projeto utilizará uma plataforma (como Tray ou Nuvemshop) ou desenvolvimento personalizado. Após entender seu objetivo, apresentamos uma proposta transparente sem custos ocultos.',
    is_visible: true,
    display_order: 1,
  },
  {
    id: 'f2',
    question: 'Qual é o prazo médio de desenvolvimento?',
    answer: 'Landing pages de alta conversão costumam ser entregues entre 7 e 15 dias. Sites institucionais e e-commerces variam de 20 a 45 dias úteis, dependendo do volume de páginas e validações.',
    is_visible: true,
    display_order: 2,
  },
  {
    id: 'f3',
    question: 'A ANXIS desenvolve lojas virtuais em quais plataformas?',
    answer: 'Trabalhamos com as principais plataformas do mercado, como Tray, Nuvemshop, WooCommerce e Loja Integrada, além de projetos de e-commerce totalmente customizados em código.',
    is_visible: true,
    display_order: 3,
  },
  {
    id: 'f4',
    question: 'Vocês utilizam templates ou criam layouts exclusivos?',
    answer: 'Criamos a estrutura e a interface de acordo com a identidade visual e o objetivo da sua empresa. Não aplicamos layouts genéricos ou cópias de templates.',
    is_visible: true,
    display_order: 4,
  },
  {
    id: 'f5',
    question: 'Eu terei facilidade para atualizar o site depois do lançamento?',
    answer: 'Sim. Estruturamos os projetos para que sua equipe possa alterar textos, produtos, imagens e banner com autonomia de forma simples.',
    is_visible: true,
    display_order: 5,
  },
  {
    id: 'f6',
    question: 'O projeto inclui versão para celular e otimização para SEO?',
    answer: 'Sim, 100% responsivo e construído com práticas técnicas de SEO (meta tags, velocidade de carregamento, hierarquia H1-H6 e dados estruturados).',
    is_visible: true,
    display_order: 6,
  },
  {
    id: 'f7',
    question: 'Como funciona o suporte pós-lançamento?',
    answer: 'Acompanhamos a fase de publicação e oferecemos período de garantia para ajustes técnicos, além de orientações práticas para o uso diário.',
    is_visible: true,
    display_order: 7,
  },
]

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'tm1',
    name: 'Dra. Erika Vieira',
    company: 'Erika Vieira Dermatologia',
    role: 'Médica Dermatologista & Fundadora',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop',
    headline: 'Nossa presença digital finalmente transmite a sofisticação e autoridade da clínica.',
    content: 'O design autoral e a velocidade de carregamento aumentaram o agendamento de consultas particulares logo no primeiro mês. O trabalho da equipe ANXIS superou todas as expectativas.',
    rating: 5,
    is_visible: true,
    display_order: 1,
  },
  {
    id: 'tm2',
    name: 'Dr. Felipe Bezerril',
    company: 'Felipe Bezerril Advocacia',
    role: 'Sócio Fundador & Advogado',
    photo_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&auto=format&fit=crop',
    headline: 'A nova landing page gerou leads altamente qualificados para consultoria jurídica.',
    content: 'A estrutura estratégica e a clareza da proposta de valor transformaram nossos resultados de tráfego pago no Google. A equipe entregou exatamente no prazo e com qualidade impecável.',
    rating: 5,
    is_visible: true,
    display_order: 2,
  },
  {
    id: 'tm3',
    name: 'Carlos Eduardo',
    company: 'Decor Studio Ambientes',
    role: 'Diretor Comercial',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
    headline: 'A reformulação da nossa loja virtual refletiu diretamente no aumento das conversões.',
    content: 'A ANXIS compreendeu com perfeição a regra de negócio do nosso catálogo. A velocidade e a experiência no celular tornaram o processo de compra dos nossos clientes muito mais ágil.',
    rating: 5,
    is_visible: true,
    display_order: 3,
  },
  {
    id: 'tm4',
    name: 'Mariana Lima',
    company: 'Pulse Software & Tech',
    role: 'Head de Marketing',
    photo_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop',
    headline: 'Nossas campanhas agora convertem com clareza, gerando alto CTR e ROI comprovado.',
    content: 'O suporte técnico prestativo e o desenvolvimento em Next.js nos deram a base sólida que precisávamos para acelerar nossos lançamentos digitais com total segurança.',
    rating: 5,
    is_visible: true,
    display_order: 4,
  },
  {
    id: 'tm5',
    name: 'Mirele Fabro',
    company: 'Mirele Fabro Psicologia',
    role: 'Psicóloga Clínica',
    photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop',
    headline: 'Uma página acolhedora, com agendamentos descomplicados e visual impecável.',
    content: 'Recebi diversos elogios de pacientes que encontraram meu consultório pelo site. A experiência de navegação transmite humanidade e confiança imediata desde o primeiro clique.',
    rating: 5,
    is_visible: true,
    display_order: 5,
  },
]
