import { Project, Technology, ServiceItem, FAQItem, Testimonial, SiteSettings } from '@/types/database.types'

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  id: 'default-settings',
  company_name: 'ANXIS',
  logo_light_url: '/images/logo-transparente.png',
  logo_dark_url: '/images/logo-transparente.png',
  email: 'contato@anxis.com.br',
  phone: '(11) 99999-9999',
  whatsapp: '5511999999999',
  address: 'São Paulo, SP - Brasil',
  social_links: {
    instagram: 'https://instagram.com/anxis.digital',
    linkedin: 'https://linkedin.com/company/anxis-digital',
  },
  primary_cta_label: 'Solicitar uma proposta',
  primary_cta_url: '#contato',
}

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 's1',
    title: 'Sites Institucionais',
    description: 'Apresente sua empresa com clareza, credibilidade e uma estrutura moderna preparada para gerar novas oportunidades.',
    icon: 'Globe',
    benefits: [
      'Design responsivo sob medida',
      'Otimização de velocidade & SEO',
      'Gestão simples de conteúdos'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 1,
  },
  {
    id: 's2',
    title: 'Landing Pages',
    description: 'Páginas focadas em campanhas de tráfego pago, lançamentos e geração contínua de oportunidades qualificadas.',
    icon: 'Zap',
    benefits: [
      'Estrutura focada em conversão',
      'Rastreamento nativo de UTMs & Meta Pixel',
      'Integração direta com seu CRM'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 2,
  },
  {
    id: 's3',
    title: 'Lojas Virtuais',
    description: 'Projetos de e-commerce voltados para a melhor experiência de compra do cliente e gestão ágil do catálogo.',
    icon: 'ShoppingBag',
    benefits: [
      'Nuvemshop, Tray ou WooCommerce',
      'Checkout otimizado e seguro',
      'Integração com ERPs e fretes'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 3,
  },
  {
    id: 's4',
    title: 'Reformulação de Sites',
    description: 'Modernização de sites legados com melhorias de interface, arquitetura da informação e performance.',
    icon: 'RefreshCw',
    benefits: [
      'Migração segura de SEO',
      'Nova identidade tecnológica',
      'Carregamento instantâneo'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 4,
  },
  {
    id: 's5',
    title: 'Projetos Personalizados',
    description: 'Desenvolvimento em código para demandas complexas e regras de negócio que não cabem em plataformas prontas.',
    icon: 'Code2',
    benefits: [
      'Next.js, React e TypeScript',
      'Arquitetura escalável',
      'APIs e microsserviços sob medida'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 5,
  },
  {
    id: 's6',
    title: 'Integrações e Melhorias',
    description: 'Conexão com ferramentas externas, meios de pagamento, automações de e-mail e melhorias de funcionalidades.',
    icon: 'Cpu',
    benefits: [
      'Automação de processos',
      'Webhooks e APIs RESTful',
      'Suporte técnico contínuo'
    ],
    link: '#contato',
    is_visible: true,
    display_order: 6,
  },
]

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'Decor Design - E-commerce de Alto Padrão',
    client: 'Decor Studio (Projeto Demonstrativo)',
    category: 'e-commerce',
    short_description: 'Loja virtual desenvolvida para e-commerce de decoração e iluminação com catálogo dinâmico e experiência fluida.',
    desktop_image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faAEA6?q=80&w=1200&auto=format&fit=crop',
    mobile_image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faAEA6?q=80&w=600&auto=format&fit=crop',
    project_url: 'https://decor-demo.anxis.com.br',
    button_label: 'Ver Demonstração',
    open_new_tab: true,
    technologies: ['Tray', 'JavaScript', 'CSS3', 'HTML5'],
    year: '2026',
    accent_color: '#0075FF',
    image_alt: 'Preview do projeto Decor Design E-commerce',
    is_featured: true,
    is_visible: true,
    display_order: 1,
  },
  {
    id: 'p2',
    title: 'Apex Financial Services - Portal Institucional',
    client: 'Apex Group (Projeto Demonstrativo)',
    category: 'institucional',
    short_description: 'Plataforma institucional corporativa com foco em posicionamento de mercado e facilidade de atendimento.',
    desktop_image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    mobile_image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=600&auto=format&fit=crop',
    project_url: 'https://apex-demo.anxis.com.br',
    button_label: 'Ver Demonstração',
    open_new_tab: true,
    technologies: ['Next.js', 'Tailwind CSS', 'TypeScript'],
    year: '2026',
    accent_color: '#168CFF',
    image_alt: 'Preview do projeto Apex Financial Services',
    is_featured: true,
    is_visible: true,
    display_order: 2,
  },
  {
    id: 'p3',
    title: 'Pulse SaaS - Landing Page de Alta Conversão',
    client: 'Pulse Software (Projeto Demonstrativo)',
    category: 'landing-page',
    short_description: 'Landing page para captação de leads em campanhas de tráfego pago para software de gestão empresarial.',
    desktop_image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    mobile_image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop',
    project_url: 'https://pulse-demo.anxis.com.br',
    button_label: 'Ver Demonstração',
    open_new_tab: true,
    technologies: ['React', 'Zod', 'Motion', 'Tailwind CSS'],
    year: '2026',
    accent_color: '#081D3A',
    image_alt: 'Preview da Landing Page Pulse SaaS',
    is_featured: false,
    is_visible: true,
    display_order: 3,
  },
  {
    id: 'p4',
    title: 'Nexus Hub - Portal Customizado & Área Restrita',
    client: 'Nexus Systems (Projeto Demonstrativo)',
    category: 'personalizado',
    short_description: 'Sistema web sob medida com controle de acesso, dashboards e integrações via Webhooks e APIs RESTful.',
    desktop_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    mobile_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop',
    project_url: 'https://nexus-demo.anxis.com.br',
    button_label: 'Ver Demonstração',
    open_new_tab: true,
    technologies: ['Next.js', 'Supabase', 'TypeScript', 'Tailwind CSS'],
    year: '2026',
    accent_color: '#0075FF',
    image_alt: 'Preview do projeto Nexus Hub',
    is_featured: false,
    is_visible: true,
    display_order: 4,
  },
]

export const INITIAL_TECHNOLOGIES: Technology[] = [
  { id: 't1', name: 'Tray', logo_url: 'https://cdn.svgporn.com/logos/tray.svg', category: 'E-commerce', is_visible: true, display_order: 1 },
  { id: 't2', name: 'Nuvemshop', logo_url: 'https://cdn.svgporn.com/logos/nuvemshop.svg', category: 'E-commerce', is_visible: true, display_order: 2 },
  { id: 't3', name: 'WordPress', logo_url: 'https://cdn.svgporn.com/logos/wordpress-icon.svg', category: 'CMS', is_visible: true, display_order: 3 },
  { id: 't4', name: 'WooCommerce', logo_url: 'https://cdn.svgporn.com/logos/woocommerce-icon.svg', category: 'E-commerce', is_visible: true, display_order: 4 },
  { id: 't5', name: 'Next.js', logo_url: 'https://cdn.svgporn.com/logos/nextjs-icon.svg', category: 'Framework', is_visible: true, display_order: 5 },
  { id: 't6', name: 'React', logo_url: 'https://cdn.svgporn.com/logos/react.svg', category: 'Frontend', is_visible: true, display_order: 6 },
  { id: 't7', name: 'TypeScript', logo_url: 'https://cdn.svgporn.com/logos/typescript-icon.svg', category: 'Linguagem', is_visible: true, display_order: 7 },
  { id: 't8', name: 'Tailwind CSS', logo_url: 'https://cdn.svgporn.com/logos/tailwindcss-icon.svg', category: 'Styling', is_visible: true, display_order: 8 },
  { id: 't9', name: 'Supabase', logo_url: 'https://cdn.svgporn.com/logos/supabase-icon.svg', category: 'Backend', is_visible: true, display_order: 9 },
  { id: 't10', name: 'Node.js', logo_url: 'https://cdn.svgporn.com/logos/nodejs-icon.svg', category: 'Backend', is_visible: true, display_order: 10 },
]

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'f1',
    question: 'Quanto custa desenvolver um site ou loja virtual?',
    answer: 'O investimento varia conforme a complexidade, número de páginas, integrações necessárias e se o projeto utilizará uma plataforma (como Tray ou Nuvemshop) ou desenvolvimento personalizado. Após entender seu objetivo, apresentamos uma proposta transparente sem custos ocultos.',
    is_visible: true,
    display_order: 1,
  },
  {
    id: 'f2',
    question: 'Qual é o prazo médio de desenvolvimento?',
    answer: 'Landing pages de alta conversão costumam ser entregues entre 7 e 15 dias. Sites institucionais e e-commerces variam de 20 a 45 dias úteis, dependendo do volume de páginas e validações.',
    is_visible: true,
    display_order: 2,
  },
  {
    id: 'f3',
    question: 'A ANXIS desenvolve lojas virtuais em quais plataformas?',
    answer: 'Trabalhamos com as principais plataformas do mercado, como Tray, Nuvemshop, WooCommerce e Loja Integrada, além de projetos de e-commerce totalmente customizados em código.',
    is_visible: true,
    display_order: 3,
  },
  {
    id: 'f4',
    question: 'Vocês utilizam templates ou criam layouts exclusivos?',
    answer: 'Criamos a estrutura e a interface de acordo com a identidade visual e o objetivo da sua empresa. Não aplicamos layouts genéricos ou cópias de templates.',
    is_visible: true,
    display_order: 4,
  },
  {
    id: 'f5',
    question: 'Eu terei facilidade para atualizar o site depois do lançamento?',
    answer: 'Sim. Estruturamos os projetos para que sua equipe possa alterar textos, produtos, imagens e banner com autonomia de forma simples.',
    is_visible: true,
    display_order: 5,
  },
  {
    id: 'f6',
    question: 'O projeto inclui versão para celular e otimização para SEO?',
    answer: 'Sim, 100% responsivo e construído com práticas técnicas de SEO (meta tags, velocidade de carregamento, hierarquia H1-H6 e dados estruturados).',
    is_visible: true,
    display_order: 6,
  },
  {
    id: 'f7',
    question: 'Como funciona o suporte pós-lançamento?',
    answer: 'Acompanhamos a fase de publicação e oferecemos período de garantia para ajustes técnicos, além de orientações práticas para o uso diário.',
    is_visible: true,
    display_order: 7,
  },
]

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'tm1',
    name: 'Carlos Eduardo',
    company: 'Decor Studio (Projeto Exemplo)',
    role: 'Diretor Comercial',
    content: 'A ANXIS compreendeu exatamente a nossa necessidade de modernizar a loja virtual. A nova navegação refletiu diretamente no aumento da taxa de conversão.',
    is_visible: true,
    display_order: 1,
  },
  {
    id: 'tm2',
    name: 'Mariana Lima',
    company: 'Pulse Software (Projeto Exemplo)',
    role: 'Head de Marketing',
    content: 'Nossa landing page de campanhas ficou extremamente rápida e elegante. O suporte durante todo o processo nos transmitiu total segurança.',
    is_visible: true,
    display_order: 2,
  },
]
